server:
  port: 8888

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dianderas/demo-microservice-config-files.git
          search-paths: "{application}"
          default-label: main