eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: members
          uri: http://localhost:8090
          predicates:
            - Path=/api/members/**
        - id: communities
          uri: http://localhost:9090
          predicates:
            - Path=/api/communities/**
